#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export PAPER_RUN_ROOT="${PAPER_RUN_ROOT:-$PWD/runs/paper_supp_$(date +%Y%m%d_%H%M%S)}"
export PAPER_REPEATS="${PAPER_REPEATS:-1}"
export PAPER_RUN_MICRO_RANDOM="${PAPER_RUN_MICRO_RANDOM:-0}"
export PAPER_RUN_DSM_CAPACITY="${PAPER_RUN_DSM_CAPACITY:-0}"
export PAPER_RUN_BP_SENSITIVITY="${PAPER_RUN_BP_SENSITIVITY:-0}"
export PAPER_RUN_MICRO_SCAN="${PAPER_RUN_MICRO_SCAN:-0}"
export PAPER_RUN_TPCC="${PAPER_RUN_TPCC:-1}"
export PAPER_TPCC_CONNS_LIST="${PAPER_TPCC_CONNS_LIST:-16}"
export PAPER_RUN_TPCH="${PAPER_RUN_TPCH:-1}"
export PAPER_TPCH_QIDS="${PAPER_TPCH_QIDS:-1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22}"
export PAPER_TPCH_QUERY_REPEATS="${PAPER_TPCH_QUERY_REPEATS:-1}"
export PAPER_TPCH_QUERY_TIMEOUT_SEC="${PAPER_TPCH_QUERY_TIMEOUT_SEC:-600}"
export PAPER_FAIL_FAST="${PAPER_FAIL_FAST:-0}"

./run_paper_experiments.sh
