#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

RUN_TPCH=0 \
RUN_TPCC=0 \
RUN_MICRO_SCAN=0 \
RUN_MICRO_RANDOM=1 \
MICRO_RANDOM_PAGES="${MICRO_RANDOM_PAGES:-1500}" \
MICRO_RANDOM_ROWS_PER_PAGE="${MICRO_RANDOM_ROWS_PER_PAGE:-4}" \
MICRO_RANDOM_PASSES="${MICRO_RANDOM_PASSES:-6}" \
MICRO_RANDOM_STRIDE="${MICRO_RANDOM_STRIDE:-997}" \
DSM_CACHE_BYTES_PER_NODE="${DSM_CACHE_BYTES_PER_NODE:-16777216}" \
FIL_READ_CACHE_MAX_PAGES="${FIL_READ_CACHE_MAX_PAGES:-16384}" \
RUN_ROOT="${RUN_ROOT:-$PWD/runs/exp_micro_random_$(date +%Y%m%d_%H%M%S)}" \
PORT="${PORT:-3334}" \
./run_monitor_workloads_compare.sh
